M48
; DRILL file KiCad 10.0.1 date 2026-05-03T13:35:03
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-03T13:35:03+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.785
%
G90
G05
T1
X180.495Y-82.41
X180.495Y-88.19
T2
X112.0Y-72.0
X112.0Y-131.0
X182.0Y-131.0
X183.0Y-72.0
T3
X159.0Y-102.8
M30
