M48
; DRILL file KiCad 10.0.1 date 2026-05-02T17:41:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-02T17:41:06+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X183.91Y-117.195
X189.69Y-117.195
T2
X104.0Y-54.0
X104.0Y-120.0
X196.0Y-54.0
X196.0Y-120.0
M30
